[env:genericCH32V003F4P6]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V003F4P6
framework = ch32v003fun
monitor_speed = 115200

; --- Upload Settings ---
; 'minichlink' is the specific tool for ch32v003fun (Fast & Lightweight)

; 1. Tell Linker to use our offset script
board_build.ldscript = generated_ch32v003_Using_bootloader.ld
board_upload.maximum_size = 10240
board_upload.maximum_ram_size = 2032

; 2. Override the upload command to flash at the specific address
; -w : Write
; $SOURCE : The compiled .bin file
; 0x08000800 : The physical address in Flash (0x08000000 base + 0x1800 offset)

; List your arguments here, indented. PlatformIO will join them with spaces.
upload_protocol = custom
upload_flags =
  --flash_start
  0x08001800
  --flash_size
  0x2800
  --I2C_main_addr
  0x49
  --path
  ".pio/build/genericCH32V003F4P6/firmware.bin"

; Pass $UPLOAD_FLAGS into your command
upload_command = $OBJCOPY -O binary $SOURCE ".pio/build/genericCH32V003F4P6/firmware.bin" &&  C:\embedded_programming\Hermes_Bluepill\Software\compiled\uploader.exe $UPLOAD_FLAGS



; --- Debug Settings ---
; 'wch-link' uses OpenOCD, which is best for VS Code visual debugging
debug_tool = wch-link

; --- Build Flags ---
build_flags =
    -flto
    -I src
    -lgcc