[env:genericCH32V003F4P6]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V003F4P6
framework = ch32v003fun
monitor_speed = 115200

; --- Upload Settings ---
; 'minichlink' is the specific tool for ch32v003fun (Fast & Lightweight)
upload_protocol = minichlink

; Use the strict 2KB linker script
board_build.ldscript = ./generated_ch32v003_For_bootloader.ld
board_upload.maximum_size = 2048
board_upload.maximum_ram_size = 2032

; Standard upload to 0x00000000

; --- Debug Settings ---
; 'wch-link' uses OpenOCD, which is best for VS Code visual debugging
debug_tool = wch-link

; --- Build Flags ---
build_flags =
    -flto
    -I src
    -lgcc